# https://github.com/conda-forge/blas-feedstock/issues/106#issuecomment-1771747983
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/python312.yaml

# zip_keys Python/Numpy matrix to build for
python:
    - 3.10.* *_cpython
    - 3.12.* *_cpython
numpy:
    - 1.23
    - 1.26

zip_keys:
  -
    - python
    - numpy

# Compiler selection
c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2019                     # [win and x86_64]
  - vs2022                     # [win and arm64]
c_compiler_version:            # [unix]
  - 12                         # [linux]
  - 16                         # [osx]
fortran_compiler:              # [unix or win64]
  - gfortran                   # [linux64 or (osx and x86_64)]
  - gfortran                   # [aarch64 or ppc64le or armv7l or s390x]
  - flang                      # [win64]
fortran_compiler_version:      # [unix or win64]
  - 12                         # [linux]
  - 12                         # [osx]
  - 5                          # [win64]

# Pinning

# blas
libblas:
  - 3.9 *netlib
libcblas:
  - 3.9 *netlib
liblapack:
  - 3.9 *netlib
liblapacke:
  - 3.9 *netlib