name: Build and Test Slycot
on:
  push:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'AUTHORS'
      - 'COPYING'
      - 'gpl-2.0.txt'
      - 'MANIFEST.in'
      - 'README.rst'

jobs:


  build-setup:
    # Super fast sniff build. If this fails, don't start the other jobs
    name: Build sdist on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Slycot
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Ubuntu
        run: |
          sudo apt-get -y install gfortran cmake --fix-missing
          sudo apt-get -y install libblas-dev liblapack-dev
          pip install scikit-build numpy scipy pytest
      - name: Create Slycot sdist
        run: python setup.py sdist

      - name: Install Slycot sdist
        run: |
          mkdir cleancwd
          cd cleancwd
          tar xfz ../dist/slycot-*.tar.gz
          cd slycot-*
          python setup.py install
      - name: Run tests
        run: pytest

  build-pip-debian:
    name: Build pip Py${{ matrix.python }}, ${{ matrix.os }}, ${{ matrix.bla_vendor}} BLA_VENDOR
    runs-on: ubuntu-20.04
    container:
      image: debian:bullseye
    needs: build-setup
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'debian'
        python:
          - '3.9'
        bla_vendor: [ 'unset' ]
#        include:
#          - os: 'debian'
#            python: '3.9'
#            bla_vendor: 'Generic'
#          - os: 'debian'
#            python: '3.9'
#            bla_vendor: 'OpenBLAS'

    steps:
      - name: Setup git
        run:  |
          apt-get -y update
          apt-get -y install git
      - name: Checkout Slycot
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Setup Debian
        if: matrix.os == 'debian'
        run: |
          apt-get -y update
          apt-get -y install python3 python3-pip
          apt-get -y install gfortran cmake --fix-missing
          case ${{ matrix.bla_vendor }} in
            unset | Generic )  apt-get -y install libblas-dev liblapack-dev ;;
            OpenBLAS        ) apt-get -y install libopenblas-dev ;;
            *)
              echo "bla_vendor option ${{ matrix.bla_vendor }} not supported"
              exit 1 ;;
          esac
      - name: Build wheel
        env:
          BLA_VENDOR: ${{ matrix.bla_vendor }}
          CMAKE_GENERATOR: Unix Makefiles
        run: |
          if [[ $BLA_VENDOR = unset ]]; then unset BLA_VENDOR; fi
          python3 -m pip install --upgrade pip
          pip3 wheel -v -w . .
          wheeldir=slycot-wheels/${{ matrix.os }}-${{ matrix.python }}-${{ matrix.bla_vendor }}
          mkdir -p ${wheeldir}
          cp ./slycot*.whl ${wheeldir}/
      - name: Save wheel
        uses: actions/upload-artifact@v2
        with:
          name: slycot-wheels
          path: slycot-wheels

  coveralls-final:
    name: Finalize parallel coveralls
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
